server:
  port: 8443
  ssl:
    enabled: true
    key-alias: alexvo
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
