server:
 port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: monolith-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/